//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentServiceProduct
    {
        public int Id { get; set; }
        public int AppointmentServiceId { get; set; }
        public System.Guid ProductId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual AppointmentService AppointmentService { get; set; }
        public virtual Product Product { get; set; }
    }
}
