//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentService()
        {
            this.AppointmentServiceProducts = new HashSet<AppointmentServiceProduct>();
            this.InvoiceServices = new HashSet<InvoiceService>();
        }
    
        public int Id { get; set; }
        public System.Guid AppointmentId { get; set; }
        public System.Guid ServiceId { get; set; }
        public Nullable<System.Guid> AssignedStaffId { get; set; }
        public Nullable<decimal> PriceAtBooking { get; set; }
        public Nullable<int> EstimatedDurationMins { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentServiceProduct> AppointmentServiceProducts { get; set; }
        public virtual Service Service { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceService> InvoiceServices { get; set; }
    }
}
