//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponUsage
    {
        public int Id { get; set; }
        public int CouponId { get; set; }
        public System.Guid InvoiceId { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.DateTime UsedOn { get; set; }
        public decimal DiscountAmount { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
