//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupon()
        {
            this.CouponUsages = new HashSet<CouponUsage>();
        }
    
        public int CouponId { get; set; }
        public System.Guid SalonId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public bool IsPercentage { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Salon Salon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponUsage> CouponUsages { get; set; }
    }
}
