//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Invoices = new HashSet<Invoice>();
            this.CouponUsages = new HashSet<CouponUsage>();
        }
    
        public System.Guid CustomerId { get; set; }
        public System.Guid SalonId { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> IsMember { get; set; }
        public Nullable<System.DateTime> LastVisitDate { get; set; }
        public Nullable<decimal> AmountSpent { get; set; }
        public string Status { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<int> LoyaltyPoints { get; set; }
        public Nullable<int> MembershipId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual Salon Salon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponUsage> CouponUsages { get; set; }
    }
}
