//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public Nullable<System.Guid> AppointmentId { get; set; }
        public Nullable<System.Guid> StaffId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
