//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GlamoraaEntities : DbContext
    {
        public GlamoraaEntities()
            : base("name=GlamoraaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AppointmentServiceProduct> AppointmentServiceProducts { get; set; }
        public virtual DbSet<AppointmentService> AppointmentServices { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DailyCashLog> DailyCashLogs { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductStock> ProductStocks { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SalonOwner> SalonOwners { get; set; }
        public virtual DbSet<Salon> Salons { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StaffAvailabilityOverride> StaffAvailabilityOverrides { get; set; }
        public virtual DbSet<StaffService> StaffServices { get; set; }
        public virtual DbSet<StaffWorkingHour> StaffWorkingHours { get; set; }
        public virtual DbSet<SubService> SubServices { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<SubServiceProduct> SubServiceProducts { get; set; }
        public virtual DbSet<StaffAttendance> StaffAttendances { get; set; }
        public virtual DbSet<StaffSubService> StaffSubServices { get; set; }
        public virtual DbSet<CouponUsage> CouponUsages { get; set; }
        public virtual DbSet<InvoiceProduct> InvoiceProducts { get; set; }
        public virtual DbSet<InvoiceService> InvoiceServices { get; set; }
        public virtual DbSet<ServiceProduct> ServiceProducts { get; set; }
    }
}
