//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public System.Guid SalonId { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<System.Guid> AppointmentId { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<bool> TokenAdvance { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Salon Salon { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
