//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStock
    {
        public int Id { get; set; }
        public System.Guid ProductId { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Operation { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
        public string Notes { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
