//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProduct
    {
        public int Id { get; set; }
        public System.Guid ServiceId { get; set; }
        public System.Guid ProductId { get; set; }
        public bool IsDefault { get; set; }
        public decimal DefaultQty { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Service Service { get; set; }
    }
}
