//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAttendance
    {
        public int AttendanceId { get; set; }
        public System.Guid StaffId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
