//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSubService
    {
        public int Id { get; set; }
        public System.Guid StaffId { get; set; }
        public int SubServiceId { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual SubService SubService { get; set; }
    }
}
