//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAvailabilityOverride
    {
        public int Id { get; set; }
        public Nullable<System.Guid> StaffId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsAvailable { get; set; }
        public string Notes { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
