//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubServiceProduct
    {
        public int SubServiceId { get; set; }
        public System.Guid ProductId { get; set; }
        public decimal QuantityRequired { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SubService SubService { get; set; }
    }
}
